import { ToastNotification } from '../components/ToastNotification';
import { AccountVerificationFormProvider } from '../components/AccountVerificationForm';
import { NonceProvider } from '../utils/NonceContext';
import '../styles.css';

export default function MyApp({ Component, pageProps, nonce }) {
  return (
    <NonceProvider nonce={nonce}>
      <AccountVerificationFormProvider>
        <Component {...pageProps} />
      </AccountVerificationFormProvider>

      <ToastNotification />
    </NonceProvider>
  );
}

MyApp.getInitialProps = async (appContext) => {
  // Nonce was generated by _document.js and stored on ctx
  const nonce = appContext.ctx.__NONCE__;
  
  return {
    nonce,
  };
};
